# Generated by Django 6.0.6 on 2026-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="allowed_email_domains",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One domain per line (e.g. example.com). Leave blank to allow all users.",
            ),
        ),
    ]
