# Generated by Django 6.0.6 on 2026-06-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="algorithm",
            field=models.CharField(
                choices=[("RS256", "RSA with SHA-2 256")], default="RS256", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[("authorization-code", "Authorization code")],
                default="authorization-code",
                max_length=44,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="hash_client_secret",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(("authorization_grant_type", "authorization-code")),
                name="application_grant_type_authorization_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(("algorithm", "RS256")),
                name="application_algorithm_rs256",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(("hash_client_secret", True)),
                name="application_hash_client_secret",
            ),
        ),
    ]
