# Generated by Django 6.0.6 on 2026-06-10 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_invitation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
