# Generated by Django 6.0.6 on 2026-06-11 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_application_algorithm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="users.team",
            ),
        ),
    ]
