# Generated by Django 6.0.6 on 2026-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_application_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_emails",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Extra email addresses allowed to sign in to this application, space separated, regardless of the team's allowed domains.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="What this application is for. Shown to the team, not to end users.",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="main_app_url",
            field=models.URLField(
                blank=True,
                help_text="The application's home page, e.g. https://my-service.gov.uk.",
            ),
        ),
    ]
