# Generated by Django 6.0.6 on 2026-06-14 08:55

import django.db.models.deletion
from django.db import migrations, models


def assign_orphans_to_team(apps, schema_editor):
    """Give any pre-existing team-less applications a team before team becomes
    required. The catch-all team has no allowed domains, so it admits everyone —
    preserving the old "team-less app allows all users" behaviour. An admin can
    move these apps to a real team afterwards."""
    Application = apps.get_model("users", "Application")
    Team = apps.get_model("users", "Team")
    orphans = Application.objects.filter(team__isnull=True)
    if orphans.exists():
        team, _ = Team.objects.get_or_create(name="Unassigned applications")
        orphans.update(team=team)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_application_additional_emails_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_orphans_to_team, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="application",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="users.team",
            ),
        ),
    ]
