# Generated by Django 6.0.6 on 2026-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_application_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
