"""
Django settings for iam project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEBUG = os.environ.get("DEBUG", "false").lower() == "true"

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("The SECRET_KEY environment variable must be set.")

ALLOWED_HOSTS = (
    os.environ.get("ALLOWED_HOSTS", "").split(",")
    if os.environ.get("ALLOWED_HOSTS")
    else []
)

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 30 days; raise (and consider preload/subdomains) once HTTPS is known
    # to be stable on the deployed domain.
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30


# Application definition

INSTALLED_APPS = [
    # Provides django.contrib.admin with the allauth-authenticated admin site
    # (users.admin_site.IAMAdminSite) as the default site.
    "users.admin_config.IAMAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "users",
    "oauth2_provider",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("DATABASE_URL"):
    DATABASES = {"default": dj_database_url.config(conn_max_age=600, ssl_require=True)}
elif os.environ.get("POSTGRES_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "iam"),
            "USER": os.environ.get("POSTGRES_USER", "iam"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "iam"),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    raise ImproperlyConfigured(
        "No database configured. Set DATABASE_URL or POSTGRES_HOST — this "
        "service requires PostgreSQL."
    )


# No password validation: this service has no passwords. Accounts authenticate
# via email login-code or Google and are created with an unusable password, so
# there is nothing to validate (AUTH_PASSWORD_VALIDATORS is left empty).


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

AUTH_USER_MODEL = "users.User"
OAUTH2_PROVIDER_APPLICATION_MODEL = "users.Application"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"

# Only allauth's backend — there is no password authentication. allauth's
# AuthenticationBackend subclasses Django's ModelBackend, so it still provides
# the admin's permission lookups; Django's password-checking ModelBackend is
# dropped deliberately.
AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*"]
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
ACCOUNT_FORMS = {"request_login_code": "users.forms.AutoEnrollRequestLoginCodeForm"}
# An authenticated session must never be backed by an unverified email: every
# OIDC token we mint asserts the user's email, so a flow that logs someone in
# before they prove control of the mailbox would let them impersonate any
# address. Login-by-code and Google both prove control, so this is invisible to
# legitimate users; it exists to stop any *other* flow (e.g. the open signup
# page) from establishing a session for an unverified address.
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# Tighten the one unauthenticated, side-effecting endpoint: requesting a login
# code both auto-enrols an account (users/forms.py) and sends a code email.
# allauth merges this over its defaults (ret.update), so only this key changes.
# The added per-recipient hourly cap (10/h/key) curbs email-bombing of any one
# address and is risk-free: no legitimate user needs that many codes for their
# own mailbox. The per-IP limits are left at allauth's defaults on purpose — a
# tighter hourly per-IP ceiling would throttle a shared egress IP (office NAT).
# That means junk-account creation across many distinct emails is still only
# loosely bounded; fully removing it needs not persisting a User until the code
# is confirmed (follow-up).
ACCOUNT_RATE_LIMITS = {
    "request_login_code": "20/m/ip,3/m/key,10/h/key",
}

if os.environ.get("GOVUK_NOTIFY_API_KEY"):
    EMAIL_BACKEND = "django_gov_notify.backends.NotifyEmailBackend"
    GOVUK_NOTIFY_API_KEY = os.environ.get("GOVUK_NOTIFY_API_KEY")
    GOVUK_NOTIFY_PLAIN_EMAIL_TEMPLATE_ID = os.environ.get(
        "GOVUK_NOTIFY_PLAIN_EMAIL_TEMPLATE_ID"
    )
elif os.environ.get("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ["EMAIL_HOST"]
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# A Google login whose email matches an existing account signs straight in to
# that account (and the Google account is linked for next time) instead of
# hitting an "account already exists" page. This is safe only because Google
# asserts verified email addresses; do not enable for providers that don't.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID"),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET"),
        },
        # openid makes the provider return an id_token (Google would anyway;
        # the Dex stand-in used in docker compose requires it).
        "SCOPE": ["openid", "profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    }
}

# allauth's Google adapter lets each endpoint be overridden, so docker compose
# points them at a local Dex server and the integration tests can drive the
# production Google code path without real Google credentials.
#
# These overrides are honoured ONLY under DEBUG. In production they are ignored
# even if the env vars are present, so a stray value (e.g. copied from
# docker-compose.yml) cannot repoint "Google" at an attacker-controlled IdP —
# which, with SOCIALACCOUNT_EMAIL_AUTHENTICATION, would let that IdP mint a
# verified login for any address. Fail closed to the real Google endpoints.
if DEBUG:
    for _key, _env in {
        "AUTHORIZE_URL": "GOOGLE_AUTHORIZE_URL",
        "ACCESS_TOKEN_URL": "GOOGLE_ACCESS_TOKEN_URL",
        "ID_TOKEN_ISSUER": "GOOGLE_ID_TOKEN_ISSUER",
    }.items():
        if os.environ.get(_env):
            SOCIALACCOUNT_PROVIDERS["google"][_key] = os.environ[_env]

_oidc_key = os.environ.get("OIDC_RSA_PRIVATE_KEY")
if not _oidc_key:
    _key_path = BASE_DIR / "oidc.key"
    if _key_path.exists():
        _oidc_key = _key_path.read_text()

OAUTH2_PROVIDER = {
    "OIDC_ENABLED": True,
    "OIDC_RSA_PRIVATE_KEY": _oidc_key,
    "OAUTH2_VALIDATOR_CLASS": "validators.OIDCValidator",
    # Short-lived access tokens (default is 10 hours). This service exists to
    # gate access, so a token should not outlive a change in authorization by
    # long. Relying parties refresh as needed. NB: refresh tokens are not
    # re-checked against the domain allowlist, so revoking access in near-real
    # time still needs explicit token revocation on domain/membership removal —
    # tracked separately; this only bounds the access-token window.
    "ACCESS_TOKEN_EXPIRE_SECONDS": 600,  # 10 minutes
    # Only the authorization-code flow is permitted (every Application is
    # constrained to the code grant), so advertise only "code" rather than the
    # toolkit default that also lists the implicit/hybrid response types no
    # client here can use. RS256-only and S256-only are trimmed from the
    # discovery document in users.views.DiscoveryInfoView.
    "OIDC_RESPONSE_TYPES_SUPPORTED": ["code"],
    "SCOPES": {
        "openid": "OpenID Connect scope",
        "profile": "User profile",
        "email": "Email address",
    },
}
